name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Tar files
        run: tar -czvf kafka-connect-snmp-latest.tgz -C target/kafka-connect-target/ .
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: kafka-connect-snmp-latest.tgz
          path: kafka-connect-snmp-latest.tgz
